import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import dashboardRouter from "./dashboard";
import productsRouter from "./products";
import categoriesRouter from "./categories";
import brandsRouter from "./brands";
import customersRouter from "./customers";
import salesRouter from "./sales";
import inventoryRouter from "./inventory";
import employeesRouter from "./employees";
import suppliersRouter from "./suppliers";
import plansRouter from "./plans";
import reportsRouter from "./reports";
import settingsRouter from "./settings";
import adminRouter from "./admin";
import downloadRouter from "./download";
import billingRouter from "./billing";
import licenseRouter from "./license";
import operationsRouter from "./operations";
import purchasingRouter from "./purchasing";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(dashboardRouter);
router.use(productsRouter);
router.use(categoriesRouter);
router.use(brandsRouter);
router.use(customersRouter);
router.use(salesRouter);
router.use(inventoryRouter);
router.use(employeesRouter);
router.use(suppliersRouter);
router.use(plansRouter);
router.use(reportsRouter);
router.use(settingsRouter);
router.use(adminRouter);
router.use(downloadRouter);
router.use(billingRouter);
router.use(licenseRouter);
router.use(operationsRouter);
router.use(purchasingRouter);

export default router;
